config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :metadata_types do
    resources :metadata, except: [:index, :show], controller: 'metadata_types/metadata'
  end
  resources :contents
  resources :copyright_permissions,  except: [:index]
  resources :organizations, except: [:index, :show]
  get 'copyright/index'

  get 'home/about'
  root 'home#index'
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :copyright_permission
  mount_uploader :file, FileUploader
  serialize :file, JSON # If useing SQLite, add this line.
  has_many :content_metadata, dependent: :destroy
  has_many :metadata, through: :content_metadata
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
    @metadata_types = MetadataType.all
    @copyright_permissions = CopyrightPermission.all
  end

  # GET /contents/1/edit
  def edit
    @metadata_types = MetadataType.all
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params.merge(user: current_user))

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:title, :file, :copyright_permission_id, metadatum_ids: [])
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p>
    <strong>Title:</strong>
    <%= content.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= content.user_id %>
  </p>

</div>

app/views/contents/_form.html.erb
<%= form_for [@metadata_type, @content] do |form| %>
  <% if @content.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

			<ul>
				<% @content.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
  <% end %>

  <div>
		<%= form.label :title, style: "display: block" %>
		<%= form.text_field :title %>
  </div>

  <div>
		<%= form.label :file, style: "display: block" %>
		<%= form.file_field :file, onchange: "validateContentFile(this)" %>
  </div>

	<div>
		<%= form.collection_select(:copyright_permission_id, @copyright_permissions, :id, :description, prompt: true) %>
	</div>

	<div>
		<% @metadata_types.each do |metadata_type| %>
			<%= metadata_type.name %>
			<br>
			<% metadata_type.metadata.each do |metadatum| %>
				<input type="checkbox" name="content[metadatum_ids][]" id="content_metadatum_ids_<%= metadatum.id %>" value="<%= metadatum.id %>">
				<%= metadatum.name %>
				<br>
			<% end %>
			<br>
		<% end %>
	</div>


  <div>
		<%= form.submit %>
  </div>
<% end %>
<%= javascript_include_tag "packs/content/test" %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Show this content", @content %> |
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/index.html.erb
<div class="row">
  <div class="col">
    <h1>Content</h1>
  </div>
  <div class="col">
    <%= link_to "ADD Content", new_content_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>File</th>
          <th>User</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @contents.each do |content| %>
          <tr>
            <td><%= content.title %></td>
            <td><%= content.file %></td>
            <td><%= content.user.email %></td>
            <td><%= link_to "Show", content %></td>
            <td><%= link_to "Edit", edit_content_path(content) %></td>
            <td><%= button_to "Destroy", content_path(content), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/show.html.erb
<%= render @content %>

<% @content.metadata.each do |metadatum| %>
  <p>
    <strong>Metadata:</strong>
    <%= metadatum.name %>
  </p>
<% end %>

<div>
  <%= link_to "Edit this content", edit_content_path(@content) %> |
  <%= link_to "Back to contents", contents_path %>

  <%= button_to "Destroy this content", @content, method: :delete %>
</div>