config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :metadata_types do
    resources :metadata, except: [:index, :show], controller: 'metadata_types/metadata'
  end
  resources :contents
  resources :copyright_permissions,  except: [:index]
  resources :organizations, except: [:index, :show]
  get 'copyright/index'

  get 'home/about'
  root 'home#index'
end

app/controllers/metadata_types/metadata_controller.rb
class MetadataTypes::MetadataController < ApplicationController
  before_action :set_metadatum, only: %i[ edit update destroy ]
  before_action :set_metadata_type, only: %i[ new edit create destory ]

  # GET /metadata/new
  def new
    @metadatum = Metadatum.new
  end

  # GET /metadata/1/edit
  def edit
  end

  # POST /metadata or /metadata.json
  def create
    @metadatum = Metadatum.new(metadatum_params)
    @metadatum.metadata_type = @metadata_type

    respond_to do |format|
      if @metadatum.save
        format.html { redirect_to @metadata_type, notice: "Metadatum was successfully created." }
        format.json { render :show, status: :created, location: @metadata_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @metadata_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metadata/1 or /metadata/1.json
  def update
    respond_to do |format|
      if @metadatum.update(metadatum_params)
        format.html { redirect_to metadata_type_path(@metadatum.metadata_type_id), notice: "Metadatum was successfully updated." }
        format.json { render :show, status: :ok, location: @metadatum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @metadatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metadata/1 or /metadata/1.json
  def destroy
    print("destroying metadatum")
    title = @metadatum.name

    if @metadatum.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to metadata_type_path(params[:metadata_type_id])
    else
      flash.now[:alert] = "There was an error deleting the metadatum."
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metadatum
      @metadatum = Metadatum.find(params[:id])
    end

    def set_metadata_type
      @metadata_type = MetadataType.find(params[:metadata_type_id])
    end

    # Only allow a list of trusted parameters through.
    def metadatum_params
      params.require(:metadatum).permit(:name, :metadata_type_id)
    end
end

app/controllers/metadata_types_controller.rb
class MetadataTypesController < ApplicationController
  before_action :set_metadata_type, only: %i[ show edit update destroy ]

  # GET /metadata_types or /metadata_types.json
  def index
    @metadata_types = MetadataType.all
  end

  # GET /metadata_types/1 or /metadata_types/1.json
  def show
    @metadata_type = MetadataType.find(params[:id])
    @metadata = @metadata_type.metadata
  end

  # GET /metadata_types/new
  def new
    @metadata_type = MetadataType.new
  end

  # GET /metadata_types/1/edit
  def edit
  end

  # POST /metadata_types or /metadata_types.json
  def create
    @metadata_type = MetadataType.new(metadata_type_params)

    respond_to do |format|
      if @metadata_type.save
        format.html { redirect_to metadata_types_path, notice: "Metadata type was successfully created." }
        format.json { render :show, status: :created, location: @metadata_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @metadata_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metadata_types/1 or /metadata_types/1.json
  def update
    respond_to do |format|
      if @metadata_type.update(metadata_type_params)
        format.html { redirect_to metadata_type_url(@metadata_type), notice: "Metadata type was successfully updated." }
        format.json { render :show, status: :ok, location: @metadata_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @metadata_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metadata_types/1 or /metadata_types/1.json
  def destroy
    @metadata_type.destroy

    respond_to do |format|
      format.html { redirect_to metadata_types_url, notice: "Metadata type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metadata_type
      @metadata_type = MetadataType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def metadata_type_params
      params.require(:metadata_type).permit(:name)
    end
end

app/helpers/metadata_types_helper.rb
module MetadataTypesHelper
end

app/views/metadata_types/_form.html.erb
<%= form_with(model: metadata_type) do |form| %>
  <% if metadata_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(metadata_type.errors.count, "error") %> prohibited this metadata_type from being saved:</h2>

      <ul>
        <% metadata_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/metadata_types/_metadata_type.html.erb
<div id="<%= dom_id metadata_type %>">
  <p>
    <strong>Metadata Type:</strong>
    <%= metadata_type.name %>
  </p>

</div>

app/views/metadata_types/edit.html.erb
<h1>Editing metadata type</h1>

<%= render "form", metadata_type: @metadata_type %>

<br>

<div>
  <%= link_to "Back to metadata type", @metadata_type %>
</div>

app/views/metadata_types/index.html.erb
<div class="row">
  <div class="col">
    <h1>Metadata Type</h1>
  </div>
  <div class="col">
    <%= link_to "ADD METADATA TYPE", new_metadata_type_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Count</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @metadata_types.each do |metadata_type| %>
          <tr>
            <td><%= metadata_type.name %></td>
            <td><%= metadata_type.metadata.count %></td>
            <td><%= link_to "Show", metadata_type %></td>
            <td><%= link_to "Edit", edit_metadata_type_path(metadata_type) %></td>
            <td><%= button_to "Destroy", metadata_type_path(metadata_type), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/metadata_types/new.html.erb
<h1>New metadata type</h1>

<%= render "form", metadata_type: @metadata_type %>

<br>

<div>
  <%= link_to "Back to metadata types", metadata_types_path %>
</div>

app/views/metadata_types/show.html.erb
<%= render @metadata_type %>

<div class="row">
  <div class="col">
    <h1>Metadata</h1>
  </div>
  <div class="col">
    <%= link_to "ADD METADATA", new_metadata_type_metadatum_path(@metadata_type.id), class: "btn btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @metadata.each do |metadatum| %>
          <%= render "metadata_types/metadata/metadatum", metadatum: metadatum %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div>
  <%= link_to "Edit this metadata type", edit_metadata_type_path(@metadata_type) %> |
  <%= link_to "Back to metadata types", metadata_types_path %>

  <%= button_to "Destroy this metadata type", @metadata_type, method: :delete %>
</div>