config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :metadata_types do
    resources :metadata, except: [:index, :show], controller: 'metadata_types/metadata'
  end
  resources :contents
  resources :copyright_permissions,  except: [:index]
  resources :organizations, except: [:index, :show]
  get 'copyright/index'

  get 'home/about'
  root 'home#index'
end

app/controllers/copyright_controller.rb
class CopyrightController < ApplicationController
  def index
    @copyright_permissions = CopyrightPermission.all
    @organizations = Organization.all
  end
end

app/helpers/copyright_helper.rb
module CopyrightHelper
end

app/views/copyright/index.html.erb
<div class="row">
	<div class="col">
		<div class="row">
			<div class="col">
				<h1>Copyright</h1>
			</div>
			<div class="col">
				<%= link_to "ADD COPYRIGHT", new_copyright_permission_path, class: "btn btn-primary" %>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Description</th>
							<th>Organization</th>
							<th>Granted</th>
							<th>Date Contacted</th>
							<th>Date of Response</th>
							<th>User</th>
							<th colspan="3">Actions</th>
						</tr>
					</thead>
					<tbody>
						<% @copyright_permissions.each do |crp| %>
							<tr>
								<td><%= crp.description %></td>
								<td><%= crp.organization.name %></td>
								<td><%= crp.granted %></td>
								<td><%= crp.date_contacted %></td>
								<td><%= crp.date_of_response %></td>
								<td><%= crp.user.email %></td>
								<td><%= link_to "Show", copyright_permission_path(crp) %></td>
								<td><%= link_to "Edit", edit_copyright_permission_path(crp) %></td>
								<td><%= button_to "Destroy", copyright_permission_path(crp), method: :delete, data: { confirm: "Are you sure?" } %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="row">
			<div class="col">
				<h1>Organization</h1>
			</div>
			<div class="col">
				<%= link_to "ADD ORGANIZATION", new_organization_path, class: "btn btn-primary" %>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Name</th>
							<th>Website</th>
							<th>Email</th>
							<th colspan="2">Actions</th>
						</tr>
					</thead>
					<tbody>
						<% @organizations.each do |org| %>
							<tr>
								<td><%= org.name %></td>
								<td><%= org.website %></td>
								<td><%= org.email %></td>
								<td><%= link_to "Edit", edit_organization_path(org) %></td>
								<td><%= button_to "Destroy", organization_path(org), method: :delete, data: { confirm: "Are you sure?" } %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>