config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :metadata_types do
    resources :metadata, except: [:index, :show], controller: 'metadata_types/metadata'
  end
  resources :contents
  resources :copyright_permissions,  except: [:index]
  resources :organizations, except: [:index, :show]
  get 'copyright/index'

  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :copyright_permission
  mount_uploader :file, FileUploader
  serialize :file, JSON # If useing SQLite, add this line.
  has_many :content_metadata, dependent: :destroy
  has_many :metadata, through: :content_metadata
end

app/models/content_metadatum.rb
class ContentMetadatum < ApplicationRecord
    belongs_to :content
    belongs_to :metadatum
end

app/models/copyright_permission.rb
class CopyrightPermission < ApplicationRecord
  belongs_to :organization
  belongs_to :user
  has_many :content
end

app/models/metadata_type.rb
class MetadataType < ApplicationRecord
    has_many :metadata, dependent: :destroy
end

app/models/metadatum.rb
class Metadatum < ApplicationRecord
  belongs_to :metadata_type
  has_many :content_metadata, dependent: :destroy
  has_many :contents, through: :content_metadata
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :copyright_permissions, dependent: :destroy
  validates :user_id, 
    inclusion: { in: -> (uid) {[uid.user_id_was]}, :message => "User_id cannot be changed" }, 
    on: :update
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

		has_many :contents

    # define user roles
    enum :role, {user: 0, admin: 99}

    # set default user role
    after_initialize :set_default_role

    private

    def set_default_role
      self.role ||= :user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_controller?(names)
        names.include?(params[:controller])
    end
    helper_method :current_controller?
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
    @metadata_types = MetadataType.all
    @copyright_permissions = CopyrightPermission.all
  end

  # GET /contents/1/edit
  def edit
    @metadata_types = MetadataType.all
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params.merge(user: current_user))

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:title, :file, :copyright_permission_id, metadatum_ids: [])
    end
end

app/controllers/copyright_controller.rb
class CopyrightController < ApplicationController
  def index
    @copyright_permissions = CopyrightPermission.all
    @organizations = Organization.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/metadata_controller.rb
class MetadataController < ApplicationController
  before_action :set_metadatum, only: %i[ show edit update destroy ]

  # GET /metadata or /metadata.json
  def index
    @metadata = Metadatum.all
  end

  # GET /metadata/1 or /metadata/1.json
  def show
  end

  # GET /metadata/new
  def new
    @metadatum = Metadatum.new
  end

  # GET /metadata/1/edit
  def edit
  end

  # POST /metadata or /metadata.json
  def create
    @metadatum = Metadatum.new(metadatum_params)

    respond_to do |format|
      if @metadatum.save
        format.html { redirect_to metadatum_url(@metadatum), notice: "Metadatum was successfully created." }
        format.json { render :show, status: :created, location: @metadatum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @metadatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metadata/1 or /metadata/1.json
  def update
    respond_to do |format|
      if @metadatum.update(metadatum_params)
        format.html { redirect_to metadatum_url(@metadatum), notice: "Metadatum was successfully updated." }
        format.json { render :show, status: :ok, location: @metadatum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @metadatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metadata/1 or /metadata/1.json
  def destroy
    @metadatum.destroy

    respond_to do |format|
      format.html { redirect_to metadata_url, notice: "Metadatum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metadatum
      @metadatum = Metadatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def metadatum_params
      params.require(:metadatum).permit(:name, :metadata_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/copyright_helper.rb
module CopyrightHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/metadata_helper.rb
module MetadataHelper
end

app/helpers/metadata_types_helper.rb
module MetadataTypesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/layouts/_alert.html.erb
<% if alert %>
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
		<%= alert %>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'SSCC', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Metadata', metadata_types_path, class: 'nav-link ' + (current_controller?('metadata_types') ? 'active' : '') %>
        </li>
        <li class="nav-item">
          <%= link_to 'Content', contents_path, class: 'nav-link ' + (current_controller?('contents') ? 'active' : '') %>
        </li>
        <li class="nav-item">
          <%= link_to 'Copyright', copyright_index_path, class: 'nav-link ' + (current_controller?('copyrights') ? 'active' : '') %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
				<% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link ' + (current_controller?('devise') ? 'active' : '') %>
          </li>
					<li class="nav-item">
						<%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
					</li>
				<% else %>
					<li class="nav-item">
						<%= button_to "Sign Up", new_user_registration_path, method: :get, class: 'btn btn-secondary' %>
					</li>
					<li class="nav-item">
						<%= link_to "Login", new_user_session_path, class: 'nav-link' %>
					</li>
				<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>	
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<%= notice %>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
		<title>CcRails</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta charset="utf-8">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
		<%= render "layouts/navbar" %>
		<div class="container pt-3">
			<%= render "layouts/notice" %>
			<%= render "layouts/alert" %>
			<%= yield %>
		</div>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>